import Card, {CardType} from "./card"

const enums = {
  ruleType: {
    zhuanZhuanMaJiang: 1,
    sanRenZhuanZhuan: 2,
    erRenZhuanZhuan: 3,
    changShaMaJiang: 4,
    lobby3Player: 5,
    lobby2Player: 6,
    lobby4Player: 7
  },

  h1: new Card(CardType.Heart, 1),
  h2: new Card(CardType.Heart, 2),
  h3: new Card(CardType.Heart, 3),
  h4: new Card(CardType.Heart, 4),
  h5: new Card(CardType.Heart, 5),
  h6: new Card(CardType.Heart, 6),
  h7: new Card(CardType.Heart, 7),
  h8: new Card(CardType.Heart, 8),
  h9: new Card(CardType.Heart, 9),
  h10: new Card(CardType.Heart, 10),
  h11: new Card(CardType.Heart, 11),
  h12: new Card(CardType.Heart, 12),
  h13: new Card(CardType.Heart, 13),

  c1: new Card(CardType.Club, 1),
  c2: new Card(CardType.Club, 2),
  c3: new Card(CardType.Club, 3),
  c4: new Card(CardType.Club, 4),
  c5: new Card(CardType.Club, 5),
  c6: new Card(CardType.Club, 6),
  c7: new Card(CardType.Club, 7),
  c8: new Card(CardType.Club, 8),
  c9: new Card(CardType.Club, 9),
  c10: new Card(CardType.Club, 10),
  c11: new Card(CardType.Club, 11),
  c12: new Card(CardType.Club, 12),
  c13: new Card(CardType.Club, 13),

  s1: new Card(CardType.Spades, 1),
  s2: new Card(CardType.Spades, 2),
  s3: new Card(CardType.Spades, 3),
  s4: new Card(CardType.Spades, 4),
  s5: new Card(CardType.Spades, 5),
  s6: new Card(CardType.Spades, 6),
  s7: new Card(CardType.Spades, 7),
  s8: new Card(CardType.Spades, 8),
  s9: new Card(CardType.Spades, 9),
  s10: new Card(CardType.Spades, 10),
  s11: new Card(CardType.Spades, 11),
  s12: new Card(CardType.Spades, 12),
  s13: new Card(CardType.Spades, 13),

  d1: new Card(CardType.Diamond, 1),
  d2: new Card(CardType.Diamond, 2),
  d3: new Card(CardType.Diamond, 3),
  d4: new Card(CardType.Diamond, 4),
  d5: new Card(CardType.Diamond, 5),
  d6: new Card(CardType.Diamond, 6),
  d7: new Card(CardType.Diamond, 7),
  d8: new Card(CardType.Diamond, 8),
  d9: new Card(CardType.Diamond, 9),
  d10: new Card(CardType.Diamond, 10),
  d11: new Card(CardType.Diamond, 11),
  d12: new Card(CardType.Diamond, 12),
  d13: new Card(CardType.Diamond, 13),

  j1: new Card(CardType.Joker, 15),
  j2: new Card(CardType.Joker, 16),
}

export default enums
